import type { Theme } from '@rtpa/shared';

export const PRESET_THEMES: Theme[] = [
  {
    id: 'preset-midnight-gala',
    name: 'Midnight Gala',
    isPreset: true,
    tokens: {
      background: { type: 'gradient', value: 'linear-gradient(135deg, #0b1026 0%, #1c2240 60%, #2a1a3e 100%)' },
      ambient: 'glow',
      frame: { style: 'thin', borderColor: '#d4af37', borderWidth: 2, radius: 10, shadow: true },
      caption: { enabled: true, bg: 'rgba(10,12,30,0.72)', color: '#f5e9c8' },
      font: "'Playfair Display', Georgia, serif",
      accent: '#d4af37',
    },
  },
  {
    id: 'preset-warm-bokeh',
    name: 'Warm Bokeh',
    isPreset: true,
    tokens: {
      background: { type: 'gradient', value: 'radial-gradient(circle at 30% 20%, #4a2c12 0%, #2a1808 70%, #160c04 100%)' },
      ambient: 'bokeh',
      frame: { style: 'rounded', borderColor: '#ffcc88', borderWidth: 3, radius: 18, shadow: true },
      caption: { enabled: true, bg: 'rgba(40,22,8,0.7)', color: '#ffe6c2' },
      font: "'Quicksand', 'Segoe UI', sans-serif",
      accent: '#ffae57',
    },
  },
  {
    id: 'preset-neon-night',
    name: 'Neon Night',
    isPreset: true,
    tokens: {
      background: { type: 'solid', value: '#05010f' },
      ambient: 'particles',
      frame: { style: 'thin', borderColor: '#ff2bd6', borderWidth: 2, radius: 6, shadow: true },
      caption: { enabled: true, bg: 'rgba(20,0,40,0.8)', color: '#5cf6ff' },
      font: "'Orbitron', 'Segoe UI', sans-serif",
      accent: '#ff2bd6',
    },
  },
  {
    id: 'preset-clean-light',
    name: 'Clean Light',
    isPreset: true,
    tokens: {
      background: { type: 'solid', value: '#f7f7f5' },
      ambient: 'none',
      frame: { style: 'rounded', borderColor: '#e2e2dc', borderWidth: 1, radius: 12, shadow: true },
      caption: { enabled: true, bg: 'rgba(255,255,255,0.9)', color: '#2b2b2b' },
      font: "'Inter', 'Helvetica Neue', sans-serif",
      accent: '#3b82f6',
    },
  },
  {
    id: 'preset-rustic-kraft',
    name: 'Rustic Kraft',
    isPreset: true,
    tokens: {
      background: { type: 'solid', value: '#c8a877' },
      ambient: 'none',
      frame: { style: 'polaroid', borderColor: '#fdf8ee', borderWidth: 12, radius: 4, shadow: true },
      caption: { enabled: true, bg: 'rgba(60,42,20,0.78)', color: '#f3e4c4' },
      font: "'Caveat', 'Comic Sans MS', cursive",
      accent: '#8a5a2b',
    },
  },
  {
    id: 'preset-garden-pastel',
    name: 'Garden Pastel',
    isPreset: true,
    tokens: {
      background: { type: 'gradient', value: 'linear-gradient(160deg, #e9f7ec 0%, #f3e9f7 50%, #e9f0f7 100%)' },
      ambient: 'bokeh',
      frame: { style: 'rounded', borderColor: '#ffffff', borderWidth: 4, radius: 20, shadow: true },
      caption: { enabled: true, bg: 'rgba(255,255,255,0.85)', color: '#4a5a4f' },
      font: "'Nunito', 'Segoe UI', sans-serif",
      accent: '#7bc4a4',
    },
  },
  {
    id: 'preset-monochrome-film',
    name: 'Monochrome Film',
    isPreset: true,
    tokens: {
      background: { type: 'solid', value: '#141414' },
      ambient: 'none',
      frame: { style: 'thin', borderColor: '#e8e8e8', borderWidth: 2, radius: 0, shadow: false },
      caption: { enabled: true, bg: 'rgba(0,0,0,0.8)', color: '#eaeaea' },
      font: "'Courier New', monospace",
      accent: '#bdbdbd',
    },
  },
  {
    id: 'preset-confetti-pop',
    name: 'Confetti Pop',
    isPreset: true,
    tokens: {
      background: { type: 'gradient', value: 'linear-gradient(135deg, #ff5e7e 0%, #ffb347 50%, #57e0ff 100%)' },
      ambient: 'particles',
      frame: { style: 'rounded', borderColor: '#ffffff', borderWidth: 5, radius: 16, shadow: true },
      caption: { enabled: true, bg: 'rgba(40,20,60,0.7)', color: '#ffffff' },
      font: "'Baloo 2', 'Segoe UI', sans-serif",
      accent: '#ff3d77',
    },
  },
  {
    id: 'preset-starfield',
    name: 'Starfield',
    isPreset: true,
    tokens: {
      background: { type: 'gradient', value: 'radial-gradient(ellipse at bottom, #1b2735 0%, #090a0f 100%)' },
      ambient: 'particles',
      frame: { style: 'thin', borderColor: '#9fb3d1', borderWidth: 1, radius: 8, shadow: true },
      caption: { enabled: true, bg: 'rgba(9,10,15,0.78)', color: '#cfe0ff' },
      font: "'Exo 2', 'Segoe UI', sans-serif",
      accent: '#6ea8ff',
    },
  },
];
